apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dental-backend
  template:
    metadata:
      labels:
        app: dental-backend
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret

      containers:
        - name: backend
          image: 292659698129.dkr.ecr.us-east-1.amazonaws.com/dental-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: dental-backend-secrets
